main: me.cookie.creeperconfetti.CreeperConfetti
name: CreeperConfetti
author: Cookie
version: 1.4
api-version: 1.19

commands:
  creeperconfetti:
    description: CreeperConfetti command
    usage: /<command>
    permissions: creeperconfetti.command

permissions:
  creeperconfetti.command:
    description: CreeperConfetti command
    default: op